// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rgs-f8Q2KG6sCzGJZkDlNeOAqRB4Ynk',
    appId: '1:840981625439:web:5a1b90cbeb0f3fa5f479ea',
    messagingSenderId: '840981625439',
    projectId: 'lmrepairserviceform',
    authDomain: 'lmrepairserviceform.firebaseapp.com',
    storageBucket: 'lmrepairserviceform.firebasestorage.app',
    measurementId: 'G-606Y2F7HCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-HaeIOYsTfTn6vmmfSjv6H18DUKozaA',
    appId: '1:840981625439:android:bc2bbdcb95f23990f479ea',
    messagingSenderId: '840981625439',
    projectId: 'lmrepairserviceform',
    storageBucket: 'lmrepairserviceform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7PF5BNMIZ7ikIcb8mA20T-1ZZmCm-k-I',
    appId: '1:840981625439:ios:c09b04ad898c1204f479ea',
    messagingSenderId: '840981625439',
    projectId: 'lmrepairserviceform',
    storageBucket: 'lmrepairserviceform.firebasestorage.app',
    iosBundleId: 'com.lmcrm.app.lmrepaireagent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7PF5BNMIZ7ikIcb8mA20T-1ZZmCm-k-I',
    appId: '1:840981625439:ios:c09b04ad898c1204f479ea',
    messagingSenderId: '840981625439',
    projectId: 'lmrepairserviceform',
    storageBucket: 'lmrepairserviceform.firebasestorage.app',
    iosBundleId: 'com.lmcrm.app.lmrepaireagent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5rgs-f8Q2KG6sCzGJZkDlNeOAqRB4Ynk',
    appId: '1:840981625439:web:664a80d54bd31f9ff479ea',
    messagingSenderId: '840981625439',
    projectId: 'lmrepairserviceform',
    authDomain: 'lmrepairserviceform.firebaseapp.com',
    storageBucket: 'lmrepairserviceform.firebasestorage.app',
    measurementId: 'G-TL0VJP4HV3',
  );
}
